### ISSUE TITLE
Crashing when moved to background

### ISSUE THREAD

**Issue by alexarje** [fourMs/MoMoCapture#1]
The app currently works on: 

- Moto G4 (Android 7)
- Samsung Galaxy A3 (Android v7).
- Sony Xperia Z2 tablet (Android 7.1.1)
- Galaxy S7 (Android 6.0.1)
- Samsung Galaxy S6 Edge

and we have confirmed crashes on: 

- Samsung Galaxy Note 8 (Android 9)
- Samsung Galaxy S9+ (Android 10)
- Nokia 8.1 (Android 10)
- OnePlus 7T Pro (Android 10)
- Google Pixel 3a (Android 10)

It does not work on: 

- Sony Xperia Z (Android 4.3)

**Comment by gutosantos82** [comment]
https://github.com/katzer/cordova-plugin-background-mode/pull/435#issuecomment-523875084
https://github.com/katzer/cordova-plugin-background-mode/issues/493
https://bitbucket.org/TheBosZ/cordova-plugin-run-in-background/src/master/

Apparently there is an issue with the background plugin for Android 9+. I will update to the TheBosZ and do some testing.

**Comment by alexarje** [comment]
Things now work, so closing this ticket.

**Comment by adekunle11** [comment]
Hello @alexarje @gutosantos82 the issue i have now is, the app works well on android 5.0, can even run for days. but on android 9 and android 10. it dies after few minutes(sometimes seconds)
i'm using the BosZ one. 
below is my manifest file
```
<uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.BIND_NOTIFICATION_LISTENER_SERVICE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
```

my js file
```
onDeviceReady: function() {
    this.receivedEvent('deviceready');
    cordova.plugins.backgroundMode.permissionOnTop();
    cordova.plugins.backgroundMode.enable();
    cordova.plugins.backgroundMode.on('activate', function () {
        cordova.plugins.backgroundMode.disableWebViewOptimizations();
        counter = 0;
        setInterval(function () {
            console.log(counter++);
            cordova.plugins.notification.badge.increase();
        }, 1000);
    });
    cordova.plugins.backgroundMode.on('deactivate', function () {
        cordova.plugins.notification.badge.clear();
    });
    cordova.plugins.backgroundMode.unlock();
    cordova.plugins.backgroundMode.disableWebViewOptimizations();
    cordova.plugins.backgroundMode.disableBatteryOptimizations();
    cordova.plugins.backgroundMode.openBatteryOptimizationsSettings();
    cordova.plugins.backgroundMode.overrideBackButton();
    cordova.plugins.backgroundMode.excludeFromTaskList();
    cordova.plugins.backgroundMode.configure({ text: "App is running oh" });
    },
```

**Comment by gutosantos82** [comment]
Hi @adekunle11 , I'm sorry but we are not the plugin developer. We just use the plugins.

**Comment by adekunle11** [comment]
> Hi @adekunle11 , I'm sorry but we are not the plugin developer. We just use the plugins.

@gutosantos82 I know. I wanted to know if you were able to get it to work

**Comment by gutosantos82** [comment]
Oh, ok. We haven't run extensive tests so far. We will run an experiment with this app this month. I let you know how it goes in terms of Android users. I have seen similar problems reported on the plugins Github page. Not sure if they were able to solve.

**Comment by danielehrhardt** [comment]
> Oh, ok. We haven't run extensive tests so far. We will run an experiment with this app this mon

Hi i have the same Problems like @adekunle11
How is your testing going?
